<?php
$_helper = $this->helper('WeltPixel\LazyLoading\Helper\Data');
$imageLoader = $_helper->getImageLoader();
?>
<script type="text/javascript">
    window.wpLazyLoad = window.wpLazyLoad || {};
    window.wpLazyLoad.effect = "fadeIn";
    window.wpLazyLoad.effectspeed = 1000;
    window.wpLazyLoad.imageloader = "<?php echo $imageLoader ?>";
    window.wpLazyLoad.threshold = "0";
    require(['jquery', 'WeltPixel_LazyLoading/js/jquery_lazyload'], function($) {
        $("img.lazy").lazyload({
            effect: "fadeIn",
            effectspeed: 1000,
            imageloader: "<?php echo $imageLoader ?>"
        });
    });
</script>
