<?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

$_weltpixelHelper = $this->helper('WeltPixel\ProductPage\Helper\Data');
$removeWishlist = $_weltpixelHelper->removeWishlist();
$removeCompare = $_weltpixelHelper->removeCompare();
$addToCartClass = !$block->shouldRenderQuantity() ? 'full-width-add-to' : '';
$addToClass = !$removeWishlist && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$removeCompare ? 'addto-fullwidth' : '';
?>

<?php if ((!$removeWishlist  && $this->helper('Magento\Wishlist\Helper\Data')->isAllow()) || !$removeCompare): ?>
    <div class="product-addto-links <?php echo $addToCartClass; ?> <?php echo $addToClass ?>" data-role="add-to-links">
        <?php if (!$removeWishlist && $this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
            <a href="#"
                class="action towishlist"
                data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
                data-action="add-to-wishlist"><span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span></a>
        <?php endif; ?>
        <?php if (!$removeCompare) :  ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
            data-role="add-to-links"
            class="action tocompare"><span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span></a>
        <?php endif; ?>
    </div>
    <script type="text/x-magento-init">
        {
            "body": {
                "addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
            }
        }
    </script>
<?php endif; ?>