<?php $_helper = $this->helper('WeltPixel\ProductPage\Helper\Data'); ?>
<?php $_mobileHelper = $this->helper('WeltPixel\MobileDetect\Helper\Data'); ?>
<?php $positionProductInfo = $_helper->getPositionProductInfo($_helper->getStoreId()) ?>
<?php $mobileBreakpoint = $_helper->getMobileThreshold($_helper->getStoreId()) + 1 ?>
<?php $isMobile = $_mobileHelper->isMobile() ?>
<div id="swipeOff"></div>
<script>
require(['jquery', 'productPage', 'mage/mage', 'mage/gallery/gallery'],
	function ($, productPage) {
        window.positionProductInfo = '<?php echo $positionProductInfo ?>';
        window.isMobile = '<?php echo $isMobile ?>';
        window.wpMobileBreakpoint = '<?php echo $mobileBreakpoint ?>';

        var positionProductInfo = window.positionProductInfo;
        var isMobileCheck = productPage.isMobileCheck();

        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
            if($(window).width() > <?= $mobileBreakpoint ?>){
                $(this).on('fotorama:load', function() {
                    var  api = $(this).data('gallery');
                    var fotoramaData = api.fotorama.data;
                    for (var i = 0; i < fotoramaData.length; i++) {
                        var imgSrc = fotoramaData[i].img;
                        if (i < 3) {
                            jQuery(jQuery('.fotorama__stage .fotorama__img').get(i)).attr('src', imgSrc);
                        }
                    }
                });
            }
        });


        $(document).ready(function () {
            productPage.init();
        });

        $(window).on('load',function () {
            productPage.load();
            jQuery('html, body').animate({scrollTop: 0}, 'fast');
            if (positionProductInfo == 1 && !isMobileCheck) {
                productPage.bindStickyScroll();
            }
            $('.product-info-main').removeClass('pp-floating-v4');
            if(!isMobileCheck && $('.product-info-main').hasClass('product_v4')) {
                $('.product-info-main').addClass('pp-floating-v4');
            }

        });

        $(document).ajaxComplete(function () {
            productPage.ajaxComplete();
        });


        var reinitTimer;
        $(window).on('resize', function () {
            clearTimeout(reinitTimer);
            reinitTimer = setTimeout(productPage.resize(), 100);
            if (positionProductInfo == 1 && !isMobileCheck) {
                productPage.bindStickyScroll();
            }
        });

    }
);
</script>
