<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

$_helper = $this->helper('WeltPixel\AdvanceCategorySorting\Helper\Data');
$groupSettings = $_helper->getConfigValuesByGroup('general');
$displaySortByDesktop = '';
$displaySortByMobile = '';
if ($groupSettings['enable'] === '1') {
    $displaySortByDesktop = ($_helper->isSortByEnabledOnDesktop() == '1' ? 'sort-by-desktop' : 'sort-by-desktop-disabled');
    $displaySortByMobile = ($_helper->isSortByEnabledOnMobile() == '1' ? 'sort-by-mobile' : 'sort-by-mobile-disabled');
}
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label <?php echo $displaySortByDesktop ?> <?php echo $displaySortByMobile ?>" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
