<section class="contact contact--phones">
    <h2 class="contact__title contact__title--phones">Phones</h2>
    
    <dl class="contact__list contact__list--phones">
        <div class="contact__item contact__item--phones">
            <dt class="contact__label contact__label--phones"><?= $block->escapeHtml(__('Client service')) ?></dt>
            <dd class="contact__value contact__value--phones">
                <a href="tel:+13122390843" class="contact__link contact__link--phones"><?= $block->escapeHtml(__('+1 312-239-0843')) ?></a>
            </dd>
        </div>
        
        <div class="contact__item contact__item--phones">
            <dt class="contact__label contact__label--phones"><?= $block->escapeHtml(__('Support team')) ?></dt>
            <dd class="contact__value contact__value--phones">
                <a href="tel:+380443621209" class="contact__link contact__link--phones"><?= $block->escapeHtml(__('+380 (044) 362-12-09')) ?></a>
            </dd>
        </div>
        
        <div class="contact__item contact__item--phones">
            <dt class="contact__label contact__label--phones"><?= $block->escapeHtml(__('Department of Human Resources')) ?></dt>
            <dd class="contact__value contact__value--phones">
                <a href="tel:+380934454887" class="contact__link contact__link--phones"><?= $block->escapeHtml(__('+380 (093) 445-48-87')) ?></a>
            </dd>
        </div>
    </dl>
</section>