<?php
/**
 * @var WeltPixel\FullPageScroll\Block\FullPageScroll $_blocks
 */
$_blocks      = $block->cmsBlockFiltered();
$_countBlocks = count( $_blocks );
$_helperCustomHeader = $this->helper('WeltPixel\CustomHeader\Helper\Data');
?>
<?php if($block->enable() && $_countBlocks > 0): ?>
	<div id="fullpage">
		<?php
		foreach ( $_blocks as $_block ) {
			echo /* @escapeNotVerified */ $_block;
		}
		?>
		<div
			class="section fp-auto-height"
			for="footer"
			id="section<?php echo /* @escapeNotVerified */ $_countBlocks; ?>">
		</div>
	</div>
	<script type="text/javascript">
        require(['jquery', 'fullpagescroll'],
			function ($, FullPageScroll) {
		        window.stickyEnabled = <?php echo $_helperCustomHeader->stickyHeaderIsEnabled() ?>;
				FullPageScroll.action(<?php echo /* @escapeNotVerified */ $_countBlocks; ?>);
				jQuery(window).trigger('resize');
			});
	</script>
<?php endif; ?>
