<?php

$_category = $block->getSelectedCategory();
$_helper = $this->helper(WeltPixel\NavigationLinks\Helper\Subcategories::class);
$categoryGridColsNr = $block->getData('number_of_columns');
$categoryTitlePosition = $block->getData('title_position');
$categoryShowDescription = $block->getData('display_description');
$gridColNr = ($categoryGridColsNr) ? $categoryGridColsNr : '4';

if ($_category) :
    $subcategories = $_helper->getSubcategories($_category);
?>
<div class="wp-subcategories-widget">
    <ul class="wp-subcategories-grid wp-subcategories-col-<?= $gridColNr ?>">
    <?php foreach ($subcategories as $subcateg) : ?>
        <?php
        $subCategoryImage = $subcateg->getData('weltpixel_sc_image');
        if (!$subCategoryImage) {
            $subCategoryImage = $block->getViewFileUrl('Magento_Catalog::images/product/placeholder/image.jpg');
        } else {
            $subCategoryImage = $block->getMediaUrl() . $subCategoryImage;
            $subCategoryImage = $_helper->parseMediaUrl($subCategoryImage);
        }
        ?>
    <li class="wp-subcategories-item">
        <?php if ($categoryTitlePosition == \WeltPixel\NavigationLinks\Model\Attribute\Source\SubCategoryTitlePosition::POSITION_ABOVE_IMAGE) : ?>
        <div class="wp-subcategory-name wp-subcategory-top">
            <a href="<?= $subcateg->getUrl() ?>" title="<?= $block->escapeHtml($subcateg->getName()); ?> ">
                <?= $block->escapeHtml($subcateg->getName()); ?>
            </a>
        </div>
        <?php endif; ?>
        <a class="wp-subcategories-image" href="<?= $subcateg->getUrl() ?>" title="<?= $block->escapeHtml($subcateg->getName()); ?>">
            <img src="<?= $subCategoryImage ?>"  width="350" alt="<?=  $block->escapeHtml($subcateg->getName()) ?>">
        </a>
        <?php if ($categoryTitlePosition == \WeltPixel\NavigationLinks\Model\Attribute\Source\SubCategoryTitlePosition::POSITION_UNDER_IMAGE) : ?>
        <div class="wp-subcategory-name wp-subcategory-bottom">
            <a href="<?= $subcateg->getUrl() ?>" title="<?= $block->escapeHtml($subcateg->getName()); ?> ">
                <?= $block->escapeHtml($subcateg->getName()); ?>
            </a>
        </div>
        <?php endif; ?>
        <?php if ($categoryShowDescription) : ?>
        <div class="wp-subcategory-description">
            <a href="<?= $subcateg->getUrl() ?>" title="<?= $block->escapeHtml($subcateg->getName()); ?>" class="wp-subcateg-descr-content">
                <?=  substr($block->stripTags($subcateg->getDescription()), 0, 400); ?>
            </a>
        </div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

