<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$lazyLoadHelper = null;
$isRequestAjax = false;
$pWidth = '100%';
$lazyLoadImgDataOriginal = $block->getImageUrl();
$lazyLoadIsEnabled = false;
try {
    $lazyLoadHelper = $this->helper('WeltPixel\LazyLoading\Helper\Data');
    $pWidth = $lazyLoadHelper->getPlaceholderWidth() ?? '100%';
    $isRequestAjax = $lazyLoadHelper->isRequestAjax();
    $lazyLodImgSrc = $lazyLoadHelper->getImageLoader();
    $lazyLoadIsEnabled = $lazyLoadHelper->isEnabled() ;
} catch (\Exception $ex) {}
if ($isRequestAjax) {
    $pWidth = '100%';
    $lazyLodImgSrc = $lazyLoadImgDataOriginal;
}
?>

<?php
$lazyLoadClass = '';
if ($block->getLazyLoad()) {
    $pWidth = '100%';
    $lazyLoadClass = 'owl-lazy';
} elseif ($lazyLoadIsEnabled && !$block->getOwlcarousel()) {
    $lazyLoadClass = 'lazy';
}
?>

<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>"
      style="width:<?php /* @escapeNotVerified */ echo $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @escapeNotVerified */ echo ($block->getRatio() * 100); ?>%;">
        <img class="<?= /* @escapeNotVerified */ $block->getClass() ?> <?php echo $lazyLoadClass; ?>"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
            <?php endforeach; ?>
            <?php if (!$block->getLazyLoad()): ?>
                <?php if ($lazyLoadIsEnabled && !$block->getOwlcarousel() ) : ?>
                    src="<?php /* @escapeNotVerified */ echo $lazyLodImgSrc; ?>"
                    data-original="<?php /* @escapeNotVerified */ echo $lazyLoadImgDataOriginal; ?>"
                    style="max-width:<?php echo $pWidth ?>"
                <?php else:  ?>
                    src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
                <?php endif; ?>
            <?php endif ;?>
            <?php if ($block->getHoverImageUrl()) :  ?>
                data-hoversrc="<?php /* @escapeNotVerified */ echo $block->getHoverImageUrl(); ?>"
                data-origsrc="<?php /* @escapeNotVerified */ echo $lazyLoadImgDataOriginal; ?>"
                onmouseover="this.setAttribute('data-tmp', this.src);this.src=this.getAttribute('data-hoversrc');"
                onmouseout="this.src=this.getAttribute('data-tmp')"
                onmousemove="if (this.getAttribute('data-hoversrc') != this.src) this.setAttribute('data-tmp', this.src)"
            <?php endif; ?>
             width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"
             loading="lazy"
            <?php if ($block->getLazyLoad()): ?>
                data-src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
                data-src-retina="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
                style="max-width:<?php echo $pWidth ?>"
            <?php endif; ?>
        /></span>
</span>
