<div>
    <div>
        <h2 style="color: #41362f;">Go to Products &gt; Categories (Level 1) &gt; WeltPixel Mega Menu</h2>
        <p>You will be able to configure a different display mode for each category:</p>
        <ol style="list-style-type: square; margin-left: 40px;">
            <li>Menu display mode for each level 1 category: Full Width / Sectioned / Boxed / Default Magento</li>
            <li>Number of columns for each category menu</li>
            <li>Width of the columns</li>
        </ol>
    </div>
    <div>
        <h2 style="color: #41362f; margin-top: 20px;">Go to Products &gt; Categories (any) &gt; WeltPixel Options</h2>
        <ol style="list-style-type: square; margin-left: 40px;">
            <li>Custom Link - set a custom link for any category in the menu</li>
            <li>Open in new tab - opens the custom link/category page in new tab</li>
        </ol>
    </div>
</div>