<div>
    <p>1. After changing theme settings make sure to clear related caches: Regenerate Pearl Theme CSS, Flush Magento Cache, Clear Browser Cache (if necessary also Flush JS/CSS Cache, Flush Catalog Images Files, Flush Cache Storage)</p>
    <p>2. Make sure you are changing the settings on the right store view, settings may be different in default config vs. storeview</p>
</div>
<div>
    <p>3. <b>NEW</b>: Frontend Options now available at store view level. Use different store locale options (EN, FR, ..) when using Pearl Theme on multiple store views. If using the same language on multiple store views, you should create a separate Pearl Child Theme for each store view. If you only use a single store view no action is necessary.</p>
</div>