<div>
    <div>
        <strong><?= $escaper->escapeHtml (__('Tab')) ?></strong>
    </div>
    <button type="button" class="action" data-trigger="trigger">
        <span data-bind="i18n: 'Click Here'"></span>
    </button>
    <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Popup title',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
        <div class="content">
            <?= $block->getChildHtml('product.custom.popup.content') ?>
        </div>
    </div>
</div>