<div>
    <p>It is recommended to disable any Design Elements that you don't use. </p>
    <p>When an element is disabled, the corresponding code will not be loaded, offering more speed for your store.</p>
    <p>Also, by disabling unused Design Elements you will reduce conflicts with other 3rd party functionality
        that you will install in the future.</p>
    <p>Many available features can be checked at <a href="https://pearl.weltpixel.com" target="_blank" style="text-transform: none;">https://pearl.weltpixel.com</a> demo store.</p>
</div>