<?php
$notLoginPage = $this->getCurrentPageRedirectUrl();
/** @var \WeltPixel\SocialLogin\Helper\Data $slHelper */
$slHelper = $this->helper('WeltPixel\SocialLogin\Helper\Data');
$cspNonceProvider = $slHelper->getCspNonceProvider();
?>

<script <?php if ($cspNonceProvider) echo ' nonce="' . $cspNonceProvider->generateNonce() . '" ' ?>>
    window.skipModules = <?=$this->getSkipModules();?>;
    window.queryParam = '<?=\WeltPixel\SocialLogin\Helper\Data::REFERER_STORE_PARAM_NAME ?>';
    window.isSlGuestCheckoutEnabled = "<?=$this->helper('WeltPixel\SocialLogin\Helper\Data')->isGuestCheckoutEnabled(); ?>";
    require(['slReferer']);
</script>

<form style="display:none;"
      class="form"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('sociallogin/account/loginPost', ['_secure' => true]) ?>"
      method="post"
      id="sociallogin-form"
      data-mage-init='{"validation":{}}'
>
    <?= $block->getBlockHtml('formkey') ?>
    <input id="sociallogin-referer" name="<?= \Magento\Customer\Model\Url::REFERER_QUERY_PARAM_NAME ?>" type="hidden" value="" />
    <input name="sociallogin-checkout" type="hidden" value="<?=$notLoginPage?>" />
    <input id="sociallogin-submit" type="submit" value="" />
</form>
