<div class="product data items"
     data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0, "disabledState": "disabled"}}'>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-cars">Tab1</a>
    </div>
    <div id="tab-cars" class="item content" data-role="content">
        <?= $block->getChildHtml('homepage_carousel') ?>
    </div>

    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-movies">Tab2</a>
    </div>
    <div id="tab-movies" class="item content" data-role="content">
        <?= $block->getChildHtml('custom.login.popup') ?>
    </div>
</div>
