<?php 

/** @var $block \Magento\Checkout\Block\Onepage\Success */
/** @var $viewModel \Perspective\CartProductRating\ViewModel\ProductRating */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$viewModel = $block->getData('view_model');
$item = $block->getParentBlock() ? $block->getParentBlock()->getItem() : null;
$product = $item ? $item->getProduct() : null;
$summary = $product ? $viewModel->getReviewSummary($product) : null;

?>

<?php if ($summary && $summary->getReviewsCount()): ?>
    <?php 
        $rating = (int)$summary->getRatingSummary();
        $productId = (int)$product->getId();

        $url = $product->getProductUrl();
        $reviewsCount = (int)$summary->getReviewsCount();
    ?>
    <div class="product-reviews-summary short">
        <div class="rating-summary">
            <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
            <div class="rating-result"
                 id="rating-result_<?= /* @noEscape */ $productId ?>"
                 title="<?= $block->escapeHtmlAttr($rating) ?>%">
                <span><span><?= $block->escapeHtml($rating) ?>%</span></span>
            </div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                'width:' . $block->escapeHtmlAttr($rating) . '%',
                '#rating-result_' . $productId . ' span'
            ) ?>
        </div>
        <div class="reviews-actions">
            <a class="action view" href="<?= $block->escapeUrl($url) ?>">
                <?= $block->escapeHtml($reviewsCount) ?>&nbsp;
                <span>
                    <?= ($reviewsCount == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?>
                </span>
            </a>
        </div>
    </div>
<?php endif; ?>