<?php
// @codingStandardsIgnoreFile
?>
<?php
$_helper = $this->helper('WeltPixel\CustomHeader\Helper\Data');
$customCMSBlock = $_helper->getCustomCMSStaticBlock();
$globalPromoDisplay = $_helper->getGlobalPromoMessageDisplayOptions();
$mobileBreakPoint = $_helper->getMobileBreakPoint();
?>
<?php if ($_helper->isGlobalPromoEnabled()) : ?>
<?php $globalPromoWrapperClass = ($globalPromoDisplay) ? 'display-always' : 'display-cookies'; ?>
<div class="global-notification-wrapper <?=$globalPromoWrapperClass?>" data-mage-init='{"WeltPixel_CustomHeader/js/globalPromo": {"mobileBreakPoint": <?= $mobileBreakPoint ?>}}'>
    <div class="notice-inner">
        <?php
        echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId($customCMSBlock)
            ->toHtml();
        ?>
    </div>
    <?php if (!$globalPromoDisplay) : ?>
    <a href="javascript: void(0)" class="close-global-notification icon-line-cross" aria-label="<?= __('Close Global Promo') ?>"></a>
    <?php endif; ?>
</div>
<?php endif; ?>
