<script>
    require(["jquery"], function ($) {
        $(document).ready(function() {
            var design = 'desktop';
            /* desktop  */
            if (!$('.nav-toggle').is(':visible')) {
                design = 'desktop';
            } else {
                design = 'mobile';
            }

            jQuery(window).resize(function() {
                /* desktop */
                if (!$('.nav-toggle').is(':visible')) {
                    if (design == 'mobile') {
                        $('.header_right').insertAfter('.sections.nav-sections-3.nav-sections');
                    }
                    design = 'desktop';
                } else {
                    if (design == 'desktop') {
                        $('.page-header-v3').after(jQuery('.sections.nav-sections'));
                    }
                    design = 'mobile';
                }
            });
        });
    });
</script>
