<div id="page:main-container" class="page-columns">
	<div class="admin__old">
		<div id="container" class="main-col">
			<div class="row">
				<h3 style="margin-top: 40px;"><?php echo __('Go to Products > Categories (Level 1) > WeltPixel Mega Menu'); ?></h3>
				<p><?php echo __('You will be able to configure a different display mode for each category:'); ?></p>
				<ol style="list-style-type: square; margin-left: 40px;">
					<li><?php echo __('Menu display mode for each level 1 category: Full Width / Sectioned / Boxed / Default Magento'); ?></li>
					<li><?php echo __('Number of columns for each category menu'); ?></li>
					<li><?php echo __('Width of the columns'); ?></li>
					<li><?php echo __('Add CMS blocks or custom HTML to categories - Top / Left / Right / Bottom'); ?></li>
					<li><?php echo __('Control visibility for mobile Link “ALL [category name]” at category level'); ?></li>
				</ol>
			</div>
			
			<div class="row">
				<h3 style="margin-top: 40px;"><?php echo __('Go to Products > Categories (any) > WeltPixel Options'); ?></h3>
				<ol style="list-style-type: square; margin-left: 40px;">
					<li><?php echo __('Custom Link - set a custom link for any category in the menu'); ?></li>
					<li><?php echo __('Open in new tab - opens the custom link/category page in new tab'); ?></li>
				</ol>
			</div>
		</div>
	</div>
</div>