<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
/* @var WeltPixel\OwlCarouselSlider\Helper\Products $helper */
$helper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Products');
$sliderConfiguration = $helper->getSliderConfiguration($block->getType());
$sliderConfiguration['slide_by'] = $sliderConfiguration['slide_by'] ?? 1;
$sliderConfig = json_encode($sliderConfiguration);
$helperCustom = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Custom');
$breakpointConfiguration = $helperCustom->getBreakpointConfiguration();
$displaySocial = $helperCustom->getDisplaySocial();
$breakpoint   = $breakpointConfiguration;
$enableSlider = (array_key_exists('status', $sliderConfiguration) && $sliderConfiguration['status'] == 1) ? true : false ;
$sliderNavDesignVersion = array_key_exists('nav_design', $sliderConfiguration) ? $sliderConfiguration['nav_design'] : \WeltPixel\OwlCarouselSlider\Model\Config\Source\PrevNextDesign::DESIGN1_CAROUSEL_SIDE;
$sliderPrevLabel = 'prev';
$sliderNextLabel = 'next';
$sliderNavPrevClass = 'owl-prev';
$sliderNavNextClass = 'owl-next';
if ($sliderNavDesignVersion == \WeltPixel\OwlCarouselSlider\Model\Config\Source\PrevNextDesign::DESIGN2_UNDER_CAROUSEL) {
    $sliderNavPrevClass .= ' owl-prev-bottom owl-label-show';
    $sliderNavNextClass .= ' owl-next-bottom owl-label-show';
    $sliderPrevLabel = array_key_exists('nav_prev_label', $sliderConfiguration) ? $sliderConfiguration['nav_prev_label'] : 'prev';
    $sliderNextLabel = array_key_exists('nav_next_label', $sliderConfiguration) ? $sliderConfiguration['nav_next_label'] : 'next';
}
$imageCreationOptions = [];
if ($enableSlider) {
    $imageCreationOptions['weltpixel_owlcarousel'] = true;
    if ($sliderConfiguration['lazyLoad']) {
        $imageCreationOptions['weltpixel_lazyLoad'] = true;
    }
}
$currentProduct = $this->getProduct();
$listValue = '';
$listValueId = '';
$slideBy = 1;
$gtmHelper = null;
$gtmHelperClassName = '';
try {
    $gtmHelper = $this->helper('WeltPixel\GA4\Helper\Data');
    $gtmHelperClassName = 'WeltPixel\GA4\Helper\Data';
} catch (\Exception $ex) {}
try {
    $gtmHelper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');
    $gtmHelperClassName = 'WeltPixel\GoogleTagManager\Helper\Data';
} catch (\Exception $ex) {}
$productLabelsHelper = null;
$productLabelsEnabled = false;
$productLabelsEnabledForRelated = false;
$productLabelsEnabledForUpsell = false;
$productLabelsEnabledForCrossell = false;
try {
    $productLabelsHelper = $this->helper('WeltPixel\ProductLabels\Helper\Data');
    $productLabelsEnabledForRelated = $productLabelsHelper->enableForRelatedProducts();
    $productLabelsEnabledForUpsell = $productLabelsHelper->enableForUpsellProducts();
    $productLabelsEnabledForCrossell = $productLabelsHelper->enableForCrossellProducts();
} catch (\Exception $ex) {}
?>
<?php

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $slideBy = $sliderConfiguration['slide_by'];
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
            $listValue = $currentProduct->getName() . ' ' . __('Related Products');
            $listValueId = 'related_products';
            $productLabelsEnabled = $productLabelsEnabledForRelated;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();
            $slideBy = $sliderConfiguration['slide_by'];

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
            $listValue = $currentProduct->getName() . ' ' . __('Related Products');
            $listValueId = 'related_products';
            $productLabelsEnabled = $productLabelsEnabledForRelated;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = $currentProduct->getName() . ' ' . __('Upsell Products');
            $listValueId = 'upsell_products';
            $productLabelsEnabled = $productLabelsEnabledForUpsell;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = $currentProduct->getName() . ' ' . __('Upsell Products');
            $listValueId = 'upsell_products';
            $productLabelsEnabled = $productLabelsEnabledForUpsell;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('More Choices:');
            $items = $block->getItemCollection();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = __('Crossel Products');
            $listValueId = 'crossell_products';
            $productLabelsEnabled = $productLabelsEnabledForCrossell;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('More Choices:');
            $items = $block->getItems();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = __('Crossel Products');
            $listValueId = 'crossel_products';
            $productLabelsEnabled = $productLabelsEnabledForCrossell;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('New Products');
            $items = $exist;
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
            $listValue = __('New Products');
            $listValueId = 'new_products';
            $productLabelsEnabled = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist):?>

    <?php if($enableSlider) : ?>
    <script>
        require(['jquery', 'owl_carousel', 'owl_config' ],
            function ($) {
				 $(document).ready(function(){
                var products_type = '<?php echo $type;?>',
                    slider_config = <?php echo $sliderConfig; ?>,

                    carouselElement = $('.owl-carousel-products-' + products_type),

	                windowWidth = $(window).width(),
	                carouselWidth = carouselElement.width(),
	                carouselContainer = carouselWidth + 120,

                    items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),

	                stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,

	                sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
	                sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
	                sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
	                sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0,
                    rtl = parseInt(slider_config.rtl) == 1 ? true : false,
                    navClass = [ '<?= $sliderNavPrevClass ?>', '<?= $sliderNavNextClass ?>' ],
                    navText = [ '<?= $sliderPrevLabel ?>', '<?= $sliderNextLabel ?>' ];

                 if (rtl) {
                     navClass = navClass.reverse();
                     navText = navText.reverse();
                 }

	            var options = {
	                nav                 :parseInt(slider_config.nav) == 1 ? true : false,
                    navClass            :navClass,
                    navText             :navText,
	                dots                :parseInt(slider_config.dots) == 1 ? true : false,
                    dotsEach            :parseInt(slider_config.dotsEach) == 1 ? true : false,
                    center              :parseInt(slider_config.center) == 1 ? true : false,
	                items               :items,
	                loop                :parseInt(slider_config.loop) == 1 ? true : false,
	                margin              :parseInt(slider_config.margin) != '' && slider_config.margin != null ? parseInt(slider_config.margin) : 0,
	                stagePadding        :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
	                lazyLoad            :parseInt(slider_config.lazyLoad) == 1 ? true : false,
	                autoplay            :parseInt(slider_config.autoplay) == 1 ? true : false,
	                autoplayTimeout     :(slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
	                autoplayHoverPause  :parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
                    navSpeed            :(parseInt(slider_config.navSpeed) > 0 && slider_config.navSpeed != null) ? parseInt(slider_config.navSpeed) : 0,
                    autoplaySpeed       :(parseInt(slider_config.navSpeed) > 0 && slider_config.navSpeed != null) ? parseInt(slider_config.navSpeed) : 0,
                    dotsSpeed           :(parseInt(slider_config.dotsSpeed) > 0 && slider_config.dotsSpeed != null) ? parseInt(slider_config.dotsSpeed) : 0,
                    rtl                 :rtl,
	                autoHeight          :false,
                    slideBy             :'<?php echo $slideBy ?>',


	                responsive:{
	                    <?php echo $breakpoint['breakpoint_1']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk1) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk1) == 1 ? true : false,
                            dotsEach        :parseInt(slider_config.dotsEach_brk1) == 1 ? true : false,
	                        items           :(slider_config.items_brk1  >= 0 && slider_config.items_brk1 != null) ? parseInt(slider_config.items_brk1) : items,
	                        center          :parseInt(slider_config.center_brk1) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_1,
	                    },
	                   <?php echo $breakpoint['breakpoint_2']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk2) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk2) == 1 ? true : false,
                            dotsEach        :parseInt(slider_config.dotsEach_brk2) == 1 ? true : false,
	                        items           :(slider_config.items_brk2  >= 0 && slider_config.items_brk2 != null) ? parseInt(slider_config.items_brk2) : items,
	                        center          :parseInt(slider_config.center_brk2) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_2,
	                    },
	                    <?php echo $breakpoint['breakpoint_3']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk3) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk3) == 1 ? true : false,
                            dotsEach        :parseInt(slider_config.dotsEach_brk3) == 1 ? true : false,
	                        items           :(slider_config.items_brk3  >= 0 && slider_config.items_brk3 != null) ? parseInt(slider_config.items_brk3) : items,
	                        center          :parseInt(slider_config.center_brk3) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_3,
	                    },
	                    <?php echo $breakpoint['breakpoint_3']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk4) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk4) == 1 ? true : false,
                            dotsEach        :parseInt(slider_config.dotsEach_brk4) == 1 ? true : false,
	                        items           :(slider_config.items_brk4  >= 0 && slider_config.items_brk4 != null) ? parseInt(slider_config.items_brk4) : items,
	                        center          :parseInt(slider_config.center_brk4) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_4,
	                    }
	                }


	            };

				// workaround for owl carousel
				// track window for owl breakpoint
				$(window).on('resize', (function (){

					var ww = $( window ).width();

					var sResp1 = <?php echo $breakpoint['breakpoint_1']; ?>;
					var sResp2 = <?php echo $breakpoint['breakpoint_2']; ?>;
					var sResp3 = <?php echo $breakpoint['breakpoint_3']; ?>;
					var sResp4 = <?php echo $breakpoint['breakpoint_4']; ?>;

					var navBtnL = carouselElement.find('.owl-prev');
					var navBtnR = carouselElement.find('.owl-next');
					if((ww >= sResp4 && slider_config.nav_brk4 != 1)
						|| (ww >= sResp3 && ww < sResp4 && slider_config.nav_brk3 != 1)
						|| (ww >= sResp2 && ww < sResp3 && slider_config.nav_brk2 != 1)
						|| (ww >= sResp1 && ww < sResp2 && slider_config.nav_brk1 != 1)
					){
						navBtnL.css('display', 'none');
						navBtnR.css('display', 'none');
					}
				}));

                 /** Lazyload bug when fewer items exist in the carousel then the ones displayed */
                carouselElement.on('initialized.owl.carousel', function(event){
                    var scopeSize = event.page.size;
                    for (var i = 0; i < scopeSize; i++){
                        var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
                        $(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
                        $(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
                    }
                    setTimeout(function(){
                        $('.owl-thumbs').each(function() {
                            if (!$('.owl-thumbs').children().length) {$(this).remove();}
                        });
                    }, 370);
                });

				// fix nav buttons display on load even when set as false
				setTimeout(function(){
				 $(window).trigger('resize');
				}, 100);
				carouselElement.owlCarousel(options);

                var carouselControls = carouselElement.find('.owl-nav');

	            if (carouselContainer >= windowWidth) {

	                carouselControls.find('.owl-prev').css({
	                    'left': 0,
	                    'top': -15
	                });
	                carouselControls.find('.owl-next').css({
	                    'right': 0,
	                    'top': -15
	                });
	            }

			});
		});
    </script>
    <?php endif;?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php else: ?>
    <div class="block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <?php endif; ?>
            <h2 class="block-title title">
                <span id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></span>
            </h2>
            <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
                        <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                    <div class="products list items product-items<?php echo $enableSlider ? ' owl-carousel-products-' . $type : ''; ?>">
                        <?php $product_item = $enableSlider ? '' : ' product-item'; ?>
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item" style="">' : '</div><div class="item product product-item" style="">' ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                            <?php endif; ?>

                            <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                <a aria-label="<?= __('Product Page Link') ?>"  <?php if ($productLabelsEnabled) : ?>
                                    data-wpproductlabel="1" data-product-id="<?php echo $_item->getId() ?>"
                                <?php endif; ?>
                                    <?php if ($gtmHelper && $gtmHelper->isProductClickTrackingEnabled()) :
                                        echo $this->helper($gtmHelperClassName)->addProductClick($_item, $iterator-1, $listValue, $listValueId);
                                    endif; ?>
                                        href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                        <?php echo $block->getImage($_item, $image, $imageCreationOptions)->toHtml(); ?>
                                    </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <div class="field choice related">
                                            <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                            <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php
                                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                        ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                           data-role="add-to-links"
                                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
                        <?php endforeach ?>
                    </div>
                    <?php if($enableSlider) : ?>
                    <div id="pre-div">
                        <?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
                        <?php if ($loaderHelper->useDefaultLoader() ) : ?>
                            <div class="cssload-loader">
                                <div class="cssload-inner cssload-one"></div>
                                <div class="cssload-inner cssload-two"></div>
                                <div class="cssload-inner cssload-three"></div>
                            </div>
                        <?php else : ?>
                            <table class="imageloader-loader">
                                <tbody>
                                <tr>
                                    <td>
                                        <img src="<?= $loaderHelper->getLoadingImageUrl() ?>" />
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        <?php endif; ?>
                    </div>
					<?php endif; ?>
                </div>
            </div>
        </div>
        <?php endif;?>
