<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_helper = $this->helper('WeltPixel\ProductPage\Helper\Data'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <div class="qty-wrapper" data-bind="scope: 'qty_change'">
                        <button class="qty-button" data-bind="click: decreaseQty">-</button>
                        <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                        <input data-bind="value: qty()"
                               type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               max="<?= $_helper->getProductMaxQty($_product) ?>"
                               value=""
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty plus-minus-input"
                               data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <button class="qty-button" data-bind="click: increaseQty">+</button>
                    </div>
                </div>
            <?php endif; ?>
            <div class="<?php echo $_helper->getAddToCartBtnPosition() ;?>">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty_change": {
                        "component": "WeltPixel_ProductPage/js/changeQty",
                        "qtyInput": "#qty"
                    }
                 }
            }
        }
    }
    </script>
<?php endif; ?>
