<?php
// @codingStandardsIgnoreFile
?>
<?php $_helper = $this->helper('WeltPixel\Multistore\Helper\Data'); ?>
<?php $_utilityHelper = $this->helper('WeltPixel\Backend\Helper\Utility'); ?>
<?php $imgHeight = $_helper->getImageHeight();
      $imgWidth = $_helper->getImageWidth();
      $dropdownWidth = '160px';?>
<?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
    <?php $bgColorStyle = $_helper->getBarBgColor() ? "style='background-color: ".$_helper->getBarBgColor() ."'" : ''?>
    <div class="switcher language switcher-language" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>" <?=$bgColorStyle?>>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?> multistore-switcher-wrapper">
                     <?php foreach ($block->getStores() as $_lang): ?>
                        <?php $image = $_helper->getImageUrl($_lang->getId()); ?>
                        <?php if ($_lang->getId() == $block->getCurrentStoreId() && ($_helper->getStoreViewOptionDesktop() == 'both' || $_helper->getStoreViewOptionDesktop() == 'store_image')): ?>
                             <img height="<?php echo $imgHeight; ?>" <?php if ($imgWidth) : ?> width="<?php echo $imgWidth; ?>" <?php endif; ?> class="switcher-selected-image" src="<?php echo $image ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>"/>
                         <?php endif; ?>
                     <?php endforeach; ?>
                    <?php if ($_helper->getStoreViewOptionDesktop() == 'both' || $_helper->getStoreViewOptionDesktop() == 'store_name'): ?>
                        <span class="selected-label"><?= $block->escapeHtml($block->getStoreName()) ?></span>
                    <?php endif; ?>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown switcher-wrapper">
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if (!$_helper->canStoreBeDisplayed($_lang->getId(), $_lang->getCode())) continue; ?>
                    <?php $image = $_helper->getImageUrl($_lang->getId()); ?>
                    <?php $inactiveImage = $_helper->getInactiveImageUrl($_lang->getId()); ?>
                        <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> <?php if ($_lang->getId() == $block->getCurrentStoreId()): echo 'active'; endif; ?> switcher-option primary-options-wrapper">
                            <?php if ($_lang->getId() == $block->getCurrentStoreId()): ?>
                                <?php if ($_helper->getStoreViewOptionDesktop() == 'both' || $_helper->getStoreViewOptionDesktop() == 'store_image'): ?>
                                    <a class="selected-option">
                                        <img class="selected-image" src="<?php echo $image ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" />
                                    </a>
                                <?php endif; ?>
                                <?php if ($_helper->getStoreViewOptionDesktop() == 'both' || $_helper->getStoreViewOptionDesktop() == 'store_name'): ?>
                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>' class="multistore-label"><?= $block->escapeHtml($_lang->getName()) ?></a>
                                <?php endif; ?>
                            <?php else: ?>
                                <?php if ($_helper->getStoreViewOptionDesktop() == 'both' || $_helper->getStoreViewOptionDesktop() == 'store_image'): ?>
                                    <a class="secondary-options-wrapper" href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>' >
                                        <img class="secondary-image" src="<?php echo $inactiveImage ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" />
                                    </a>
                                <?php endif; ?>
                                <?php if ($_helper->getStoreViewOptionDesktop() == 'both' || $_helper->getStoreViewOptionDesktop() == 'store_name'): ?>
                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>' class="multistore-label"><?= $block->escapeHtml($_lang->getName()) ?></a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <style>
        <?php
        $barWidth = $_helper->getBarWidth();

        if ($_helper->getStoreViewOptionDesktop() == 'store_image'): {
            $dropdownWidth = 'auto';
        }
        endif;
        ?>

        /*CustomHeader v2 uses .header_right class that's why there are duplicates*/
        ul.weltpixel_multistore li img,
        ul.switcher-dropdown li a img,
        ul.switcher-dropdown li a .selected-image img,
        .page-header .header_right ul.weltpixel_multistore li img,
        .page-header .header_right ul.switcher-dropdown li a img,
        .page-header .header_right ul.switcher-dropdown li a .selected-image img {
            height: <?php echo $imgHeight; ?>;
        <?php if ($imgWidth) : ?>
            width: <?php echo $imgWidth; ?>;
            min-width: <?php echo $imgWidth; ?>;
        <?php endif; ?>
        }
        .page-header .panel.wrapper .switcher .options ul.dropdown {
            min-width: <?php echo $dropdownWidth; ?>;;
        }
        <?php if(!$_utilityHelper->isPearlThemeUsed() && $barWidth):?>
        @media screen and (min-width: 768px) {
            .weltpixel_multistore {
                max-width: <?php echo $barWidth;?>
            }
        }
        <?php endif;?>
    </style>
<?php endif; ?>
