<?php

// @codingStandardsIgnoreFile

/** @var $block \WeltPixel\FrontendOptions\Block\Head\Fonts */
?>
<?php
    $loadFontsAsync = $block->isAsyncFontLoadEnabled();
    $asyncFontOptions = $block->getAsyncFontFamilyOptions();
    $fontUrl = $block->getGoogleFonts();

?>
<?php if (!$loadFontsAsync && $fontUrl) : ?>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="<?php /* @escapeNotVerified */ echo $fontUrl; ?>" rel="stylesheet">
<?php elseif ($loadFontsAsync && count($asyncFontOptions)) : ?>
    <script type="text/javascript">
        WebFontConfig = {
            google: { families: <?= json_encode($asyncFontOptions) ?> }
        };
        (function() {
            var wf = document.createElement('script');
            wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js';
            wf.type = 'text/javascript';
            wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })(); </script>
<?php endif; ?>
